### ISSUE TITLE
George hasn't done work still

### ISSUE THREAD

**Issue by JoelBradley** [SweetPotatoChips/George#1]
He really should do some.

**Comment by GJClaridge** [comment]
George did enough to pass, he just died from tonsillitis during the last week. :sob:

**Comment by JoelBradley** [comment]
I want evidence!

**Comment by GJClaridge** [comment]
Of? Clarification please? :smile:

**Comment by JoelBradley** [comment]
That you did work!

**Comment by GJClaridge** [comment]
Because I got a mark should be evidence enough

**Comment by JoelBradley** [comment]
Fair enough! Good job buddy!
